# Generated by Django 4.2.16 on 2026-05-28 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlerSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.TextField(default='tech_job,job')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
